# Generated by Django 5.1 on 2024-08-16 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NAD', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapturedPacket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src_ip', models.CharField(max_length=15)),
                ('dst_ip', models.CharField(max_length=15)),
                ('port', models.IntegerField(blank=True, null=True)),
                ('protocol', models.CharField(max_length=10)),
                ('length', models.IntegerField()),
                ('info', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
